name: student-performance
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas
  - numpy
  - scikit-learn
  - imbalanced-learn
  - pytorch
  - optuna
  - matplotlib
  - seaborn
  - pyyaml
  - joblib
  - sqlalchemy
  - psycopg2
  - python-dotenv
  - pip
  - pip:
      - ucimlrepo
