cnn_bilstm_mat:
  model_id: cnn_bilstm_mat
  display_name: CNN-BiLSTM MAT
  dataset: student_mat
  config: configs/final/cnn_bilstm_mat.yaml
cnn_bilstm_por:
  model_id: cnn_bilstm_por
  display_name: CNN-BiLSTM POR
  dataset: student_por
  config: configs/final/cnn_bilstm_por.yaml
cnn_bilstm_oulad:
  model_id: cnn_bilstm_oulad
  display_name: CNN-BiLSTM OULAD
  dataset: oulad
  config: configs/final/cnn_bilstm_oulad.yaml
